"""Model A (configured by hand) vs Model B (generated by the AI): are they the same system?

Three levels, never mixed up:

* TEXTUAL EQUALITY      - identical serialised ISMS (same ids, same field order).
* STRUCTURAL EQUIVALENCE - same system: ids, names, field order, parameter indirection ('$p' vs 5),
  units (1 min vs 60 s), omitted library defaults, provenance and notes do NOT matter. Compared on the
  RESOLVED model through a node mapping found by graph isomorphism: nodes, connections, resources,
  parameters, rules, capacities, routing, strategies, experiments and simulation settings.
* RESULT EQUIVALENCE    - both models run with the same settings give the same KPIs (exact for deterministic
  models; within tolerance otherwise). Node/resource KPIs are compared through the same mapping.
"""

from __future__ import annotations

import json
import math
import re
from dataclasses import dataclass, field
from typing import Any

import networkx as nx
import yaml
from networkx.algorithms.isomorphism import DiGraphMatcher

from ..domain.expressions import resolve
from ..domain.isms import ISMSModel
from ..domain.units import UnitError, dimension_of, to_base
from ..library.registry import ComponentRegistry

CATEGORIES = ["nodes", "connections", "resources", "parameters", "capacities", "routing", "strategies", "rules",
              "experiments", "simulation"]
_DROP = {"provenance", "notes", "name", "label"}
_NUMERIC = ("value", "low", "mode", "high", "mean", "std")


@dataclass
class Difference:
    category: str
    item: str
    a: Any
    b: Any

    def __str__(self) -> str:
        return f"[{self.category}] {self.item}: A={self.a!r}  B={self.b!r}"


@dataclass
class SpecComparison:
    textual_equal: bool
    json_equal: bool  # same content ignoring field order (still id-sensitive)
    structurally_equivalent: bool
    node_mapping: dict[str, str] = field(default_factory=dict)  # A id -> B id
    resource_mapping: dict[str, str] = field(default_factory=dict)
    differences: list[Difference] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def by_category(self) -> dict[str, list[Difference]]:
        return {c: [d for d in self.differences if d.category == c] for c in CATEGORIES}

    def to_text(self) -> str:
        L = ["MODEL COMPARISON (A = manual, B = generated)", "",
             f"TEXTUAL EQUALITY:          {'YES' if self.textual_equal else 'NO'}",
             f"SAME JSON (any key order): {'YES' if self.json_equal else 'NO'}",
             f"STRUCTURAL EQUIVALENCE:    {'YES' if self.structurally_equivalent else 'NO'}", ""]
        for cat, diffs in self.by_category().items():
            L.append(f"{cat:<12} {'OK' if not diffs else f'{len(diffs)} difference(s)'}")
            L += [f"    - {d.item}: A={d.a!r}  B={d.b!r}" for d in diffs]
        if self.node_mapping:
            L += ["", "Node mapping A -> B:"] + [f"    {a} -> {b}" for a, b in self.node_mapping.items()]
        if self.notes:
            L += [""] + [f"NOTE: {n}" for n in self.notes]
        return "\n".join(L)


# ----------------------------------------------------------------------------- canonical form
def _canon_value(obj: Any) -> Any:
    """Units to base units, drop presentation/provenance keys, ints and floats compared numerically."""
    if isinstance(obj, dict):
        d = {k: _canon_value(v) for k, v in obj.items() if k not in _DROP}
        unit = d.get("unit")
        if isinstance(unit, str):
            try:
                dim = dimension_of(unit)
                for k in _NUMERIC:
                    if isinstance(d.get(k), (int, float)) and not isinstance(d.get(k), bool):
                        d[k] = round(to_base(float(d[k]), unit), 9)
                d["unit"] = f"<{dim.value}>"
            except (UnitError, KeyError, ValueError):
                pass
        return d
    if isinstance(obj, list):
        return [_canon_value(v) for v in obj]
    if isinstance(obj, bool) or obj is None or isinstance(obj, str):
        return obj
    if isinstance(obj, (int, float)):
        return round(float(obj), 9)
    return obj


def _node_params(model: ISMSModel, registry: ComponentRegistry, node) -> dict[str, Any]:
    try:
        comp = registry.get(node.component, node.component_version)
        params = comp.resolve_params(node.params).model_dump(mode="json")  # library defaults made explicit
    except Exception:  # noqa: BLE001 - unknown component / invalid params: compare what is written
        params = dict(node.params)
    return _canon_value(params)


def _abstract(params: dict[str, Any], res_kind: dict[str, str]) -> dict[str, Any]:
    """Params with references replaced by placeholders (used as isomorphism labels; references compared later)."""
    p = json.loads(json.dumps(params))
    for use in p.get("resources", []) or []:
        if isinstance(use, dict) and "resource" in use:
            use["resource"] = f"<{res_kind.get(use['resource'], '?')}>"
    for k in ("origin", "destination"):
        if p.get(k):
            p[k] = "<node>"
    if p.get("on_reject") not in (None, "scrap"):
        p["on_reject"] = "<node>"
    return p


def _resolved(model: ISMSModel) -> tuple[ISMSModel, list[str]]:
    res, problems = resolve(model)
    if res is None:
        return model, [f"{p}: {m}" for p, m, _ in problems]
    return res, []


def _graph(model: ISMSModel, registry: ComponentRegistry, labels: str) -> nx.DiGraph:
    res_kind = {r.id: r.kind.value for r in model.resources}
    g = nx.DiGraph()
    for n in model.nodes:
        full = _abstract(_node_params(model, registry, n), res_kind)
        lab = {"component": n.component}
        if labels == "full":
            lab |= {"params": full, "seize": sorted(res_kind.get(s.resource, "?") for s in n.seize),
                    "release": sorted(res_kind.get(r, "?") for r in n.release), "release_via": sorted(res_kind.get(r, "?") for r in n.release_via)}
        g.add_node(n.id, label=json.dumps(lab, sort_keys=True))
    outdeg = {n.id: sum(1 for e in model.edges if e.source == n.id) for n in model.nodes}
    for e in model.edges:
        p = e.probability
        if outdeg.get(e.source, 0) <= 1 and p in (None, 1, 1.0):
            p = None
        g.add_edge(e.source, e.target, p=None if p is None else round(float(p), 9))
    return g


def _match(ga: nx.DiGraph, gb: nx.DiGraph, with_edges: bool) -> dict[str, str] | None:
    gm = DiGraphMatcher(ga, gb, node_match=lambda x, y: x["label"] == y["label"],
                        edge_match=(lambda x, y: x["p"] == y["p"]) if with_edges else None)
    if gm.is_isomorphic():
        return dict(gm.mapping)
    return None


def _greedy(a: ISMSModel, b: ISMSModel) -> dict[str, str]:
    """Fallback mapping when the graphs differ: same component, in flow order."""
    def order(m: ISMSModel) -> list:
        g = nx.DiGraph([(e.source, e.target) for e in m.edges])
        g.add_nodes_from(n.id for n in m.nodes)
        try:
            ids = list(nx.lexicographical_topological_sort(g))
        except nx.NetworkXUnfeasible:  # loops (rework): document order
            ids = [n.id for n in m.nodes]
        comp = {n.id: n.component for n in m.nodes}
        return [(i, comp[i]) for i in ids]
    mapping: dict[str, str] = {}
    free = order(b)
    for aid, comp in order(a):
        hit = next((x for x in free if x[1] == comp), None)
        if hit:
            mapping[aid] = hit[0]
            free.remove(hit)
    return mapping


# ----------------------------------------------------------------------------- comparison
def _load(spec: ISMSModel | str | dict) -> tuple[ISMSModel, str, Any]:
    """Accepts a model, its JSON/YAML source text or a dict. Returns (model, text, data)."""
    if isinstance(spec, ISMSModel):
        return spec, spec.model_dump_json(), json.loads(spec.model_dump_json())
    if isinstance(spec, str):
        data = yaml.safe_load(spec)  # JSON is YAML
        return ISMSModel.model_validate(data), spec, data
    return ISMSModel.model_validate(spec), json.dumps(spec), spec


def compare_model_specs(a: ISMSModel | str | dict, b: ISMSModel | str | dict, registry: ComponentRegistry) -> SpecComparison:
    a, text_a, data_a = _load(a)
    b, text_b, data_b = _load(b)
    textual = text_a == text_b
    json_eq = data_a == data_b
    ra, pa = _resolved(a)
    rb, pb = _resolved(b)
    out = SpecComparison(textual, json_eq, False)
    if pa or pb:
        out.notes.append("Parámetros sin resolver (MISSING) en " + ("A " if pa else "") + ("B" if pb else "") +
                         ": se comparan las expresiones, no los valores.")

    ga, gb = _graph(ra, registry, "full"), _graph(rb, registry, "full")
    mapping = _match(ga, gb, True)
    if mapping is None:
        mapping = _match(_graph(ra, registry, "component"), _graph(rb, registry, "component"), False) or _greedy(ra, rb)
    out.node_mapping = mapping
    D = out.differences

    def m(nid: str | None) -> str | None:
        return mapping.get(nid, f"<unmapped {nid}>") if nid else nid

    # ---- nodes
    for n in ra.nodes:
        if n.id not in mapping:
            D.append(Difference("nodes", n.id, n.component, None))
    mapped_b = set(mapping.values())
    for n in rb.nodes:
        if n.id not in mapped_b:
            D.append(Difference("nodes", n.id, None, n.component))

    # ---- resources (matched by kind + the mapped tasks that use them)
    def users(model: ISMSModel, rid: str) -> set[str]:
        u = set()
        for n in model.nodes:
            uses = [x.get("resource") for x in (n.params.get("resources") or []) if isinstance(x, dict)]
            if rid in uses or rid in [s.resource for s in n.seize] or rid in n.release or rid in n.release_via:
                u.add(n.id)
        return u
    rmap: dict[str, str] = {}
    free_b = list(rb.resources)
    for r in ra.resources:
        ua = {m(x) for x in users(ra, r.id)}
        hit = next((x for x in free_b if x.kind == r.kind and users(rb, x.id) == ua), None) or \
            next((x for x in free_b if x.kind == r.kind), None)
        if hit:
            rmap[r.id] = hit.id
            free_b.remove(hit)
        else:
            D.append(Difference("resources", r.id, r.kind.value, None))
    for x in free_b:
        D.append(Difference("resources", x.id, None, x.kind.value))
    out.resource_mapping = rmap

    def rm(rid: str | None) -> str | None:
        return rmap.get(rid, f"<unmapped {rid}>") if rid else rid

    rb_by_id = {r.id: r for r in rb.resources}
    for r in ra.resources:
        if r.id not in rmap:
            continue
        s = rb_by_id[rmap[r.id]]
        if _canon_value(r.quantity) != _canon_value(s.quantity):
            D.append(Difference("resources", f"{r.id}.quantity", r.quantity, s.quantity))
        ua, ub = sorted(m(x) or "" for x in users(ra, r.id)), sorted(users(rb, s.id))
        if ua != ub:
            D.append(Difference("resources", f"{r.id}.used_by", ua, ub))
        if m(r.home) != s.home and (r.home or s.home):
            D.append(Difference("resources", f"{r.id}.home", m(r.home), s.home))
        ta, tb = r.travel, s.travel
        if (ta is None) != (tb is None):
            D.append(Difference("resources", f"{r.id}.travel", ta is not None, tb is not None))
        elif ta and tb:
            if _canon_value(ta.speed.model_dump()) != _canon_value(tb.speed.model_dump()):
                D.append(Difference("resources", f"{r.id}.travel.speed", ta.speed.value, tb.speed.value))
            da, db = _distances(ra, r, m), _distances(rb, s, lambda x: x)
            if da != db:
                D.append(Difference("resources", f"{r.id}.travel.distances", da, db))
        # strategies
        if r.dispatch != s.dispatch:
            D.append(Difference("strategies", f"{r.id}.dispatch", r.dispatch.value, s.dispatch.value))
        elif r.dispatch.value == "priority":
            oa = _priority_order(ra, r.id, m)
            ob = _priority_order(rb, s.id, lambda x: x)
            if oa != ob:
                D.append(Difference("strategies", f"{r.id}.priority_order", oa, ob))
        if r.wip_target or s.wip_target:
            wa = _wip(r.wip_target, m)
            wb = _wip(s.wip_target, lambda x: x)
            for k in sorted(set(wa) | set(wb)):
                if wa.get(k) != wb.get(k):
                    D.append(Difference("strategies", f"{r.id}.wip_target.{k}", wa.get(k), wb.get(k)))

    # ---- node parameters, capacities, rules (seize/release)
    nb = {n.id: n for n in rb.nodes}
    for n in ra.nodes:
        if n.id not in mapping or mapping[n.id] not in nb:
            continue
        o = nb[mapping[n.id]]
        if n.component != o.component:
            D.append(Difference("nodes", f"{n.id}.component", n.component, o.component))
            continue
        pa_, pb_ = _node_params(ra, registry, n), _node_params(rb, registry, o)
        for k in sorted(set(pa_) | set(pb_)):
            va, vb = pa_.get(k), pb_.get(k)
            if k == "resources":
                va = sorted(rm(x["resource"]) or "" for x in (va or []))
                vb = sorted(x["resource"] for x in (vb or []))
            elif k in ("origin", "destination") or (k == "on_reject" and va not in (None, "scrap")):
                va = m(va)
            if va != vb:
                D.append(Difference("capacities" if k in ("capacity", "fleet", "loading_area") else "parameters",
                                    f"{n.id}.{k}", va, vb))
        sa, sb = sorted(rm(s.resource) or "" for s in n.seize), sorted(s.resource for s in o.seize)
        if sa != sb:
            D.append(Difference("rules", f"{n.id}.seize", sa, sb))
        la, lb = sorted(rm(x) or "" for x in n.release), sorted(o.release)
        if la != lb:
            D.append(Difference("rules", f"{n.id}.release", la, lb))
        va = {rm(k): m(v) for k, v in n.release_via.items()}
        if va != o.release_via:
            D.append(Difference("rules", f"{n.id}.release_via", va, o.release_via))
    ca = sorted(c.description for c in ra.custom_rule_candidates if c.status != "rejected")
    cb = sorted(c.description for c in rb.custom_rule_candidates if c.status != "rejected")
    if ca != cb:
        D.append(Difference("rules", "custom_rule_candidates", ca, cb))

    # ---- connections and routing
    def edges(model: ISMSModel, f) -> dict[tuple, Any]:
        outdeg = {n.id: sum(1 for e in model.edges if e.source == n.id) for n in model.nodes}
        res = {}
        for e in model.edges:
            p = e.probability
            if outdeg.get(e.source, 0) <= 1 and p in (None, 1, 1.0):
                p = None
            res[(f(e.source), f(e.target))] = _canon_value(p)
        return res
    ea, eb = edges(ra, m), edges(rb, lambda x: x)
    for k in sorted(set(ea) | set(eb), key=str):
        if k not in ea or k not in eb:
            D.append(Difference("connections", f"{k[0]} -> {k[1]}", k in ea, k in eb))
        elif ea[k] != eb[k]:
            D.append(Difference("routing", f"{k[0]} -> {k[1]}.probability", ea[k], eb[k]))

    # ---- experiments (factor targets = the model fields they control)
    xa, xb = _experiments(a, m, rm), _experiments(b, lambda x: x, lambda x: x)
    if xa != xb:
        D.append(Difference("experiments", "factors", xa, xb))

    # ---- simulation settings
    sa_, sb_ = _sim(ra), _sim(rb)
    for k in sorted(sa_):
        if sa_[k] != sb_[k]:
            D.append(Difference("simulation", k, sa_[k], sb_[k]))

    out.structurally_equivalent = not D and not pa and not pb
    return out


def _distances(model: ISMSModel, r, m) -> dict[tuple, float]:
    """Distances between mapped task nodes (through locations), order-independent."""
    t = r.travel
    loc = {}
    for nid in {n.id for n in model.nodes}:
        loc[nid] = t.locations.get(nid, nid)
    table = {}
    for d in t.distances:
        table[frozenset((d.a, d.b))] = round(to_base(float(d.distance.value), d.distance.unit), 9)
    out = {}
    tasks = sorted(n.id for n in model.nodes if any(isinstance(x, dict) and x.get("resource") == r.id
                                                    for x in (n.params.get("resources") or [])))
    for i, x in enumerate(tasks):
        for y in tasks[i + 1:]:
            key = frozenset((loc[x], loc[y]))
            if loc[x] == loc[y]:
                val = 0.0
            elif key in table:
                val = table[key]
            elif x in {n.id for n in model.nodes if n.position} and y in {n.id for n in model.nodes if n.position}:
                px, py = model.node(x).position, model.node(y).position
                val = round(math.dist((float(px.x), float(px.y)), (float(py.x), float(py.y))), 9)
            else:
                continue
            out[tuple(sorted((m(x) or "", m(y) or "")))] = val
    return out


def _priority_order(model: ISMSModel, rid: str, m) -> list[list[str]]:
    tasks = [n for n in model.nodes if any(isinstance(x, dict) and x.get("resource") == rid for x in (n.params.get("resources") or []))]
    levels: dict[int, list[str]] = {}
    for n in tasks:
        levels.setdefault(n.priority, []).append(m(n.id) or "")
    return [sorted(levels[k]) for k in sorted(levels)]


def _wip(w, m) -> dict[str, Any]:
    if w is None:
        return {}
    return {"protected_node": m(w.protected_node), "feed_nodes": sorted(m(x) or "" for x in w.feed_nodes),
            "feeder_nodes": sorted(m(x) or "" for x in w.feeder_nodes), "target": _canon_value(w.target),
            "count_feeder_in_process": w.count_feeder_in_process, "unblock_protected": w.unblock_protected,
            "preempt_below": _canon_value(w.preempt_below)}


_REF = re.compile(r"^\$([a-z][a-z0-9_]*)$")


def _targets(model: ISMSModel, path: str, m, rm) -> list[str]:
    """Canonical model fields controlled by a factor path (a parameter controls every field that references it)."""
    mp = re.match(r"parameters\.([a-z0-9_]+)\.value$", path)
    if mp:
        ref = f"${mp.group(1)}"
        hits = []
        for n in model.nodes:
            for k, v in _flat(n.params):
                if v == ref:
                    hits.append(f"node:{m(n.id)}.{k}")
        for r in model.resources:
            for k, v in _flat(r.model_dump(mode="json", exclude={"provenance"})):
                if v == ref:
                    hits.append(f"resource:{rm(r.id)}.{k}")
        return sorted(hits) or [path]
    mn = re.match(r"nodes\.([^.]+)\.params\.(.+)$", path)
    if mn:
        return [f"node:{m(mn.group(1))}.{mn.group(2)}"]
    mr = re.match(r"resources\.([^.]+)\.(.+)$", path)
    if mr:
        return [f"resource:{rm(mr.group(1))}.{mr.group(2)}"]
    return [path]


def _flat(obj: Any, prefix: str = "") -> list[tuple[str, Any]]:
    if isinstance(obj, dict):
        return [x for k, v in obj.items() if k not in _DROP for x in _flat(v, f"{prefix}.{k}" if prefix else k)]
    if isinstance(obj, list):
        return [x for i, v in enumerate(obj) for x in _flat(v, f"{prefix}.{i}")]
    return [(prefix, obj)]


def _experiments(model: ISMSModel, m, rm) -> list:
    res = []
    for e in model.experiments:
        res.append(sorted((tuple(_targets(model, f.path, m, rm)), tuple(_canon_value(f.values))) for f in e.factors))
    return sorted(res)


def _sim(model: ISMSModel) -> dict[str, Any]:
    s = model.simulation
    return {"horizon_s": round(s.horizon.to_base(dimension_of("s")), 6), "warmup_s": round(s.warmup.to_base(dimension_of("s")), 6),
            "kind": s.kind, "replications": s.replications, "base_seed": s.base_seed, "dispatch_timing": s.dispatch_timing}


# ----------------------------------------------------------------------------- results
@dataclass
class ResultComparison:
    equivalent: bool
    rows: list[dict[str, Any]]
    rel_tol: float

    def to_text(self) -> str:
        L = [f"RESULT EQUIVALENCE: {'YES' if self.equivalent else 'NO'} (rel. tol. {self.rel_tol:g})", "",
             f"{'KPI':<52}{'A':>14}{'B':>14}  OK"]
        L += [f"{r['kpi']:<52}{r['a']:>14.6g}{r['b']:>14.6g}  {'✓' if r['ok'] else '✗'}" for r in self.rows]
        return "\n".join(L)


_GROUPS = ("units_completed", "throughput_per_hour", "avg_wip", "max_wip", "avg_lead_time_s", "p90_lead_time_s", "units_scrapped")
_NODE_KPIS = ("utilization", "starved", "blocked", "waiting_resource", "processed", "avg_content")
_RES_KPIS = ("utilization", "working", "walking", "transporting", "idle")


def compare_results(res_a, res_b, cmp: SpecComparison, rel_tol: float = 1e-9) -> ResultComparison:
    """Compare KPIs of two runs (production, throughput, WIP, lead time, utilisations, starvation, blocking,
    transport/walking), mapping node and resource ids A -> B."""
    ka, kb = res_a.kpis, res_b.kpis
    rows = []

    def add(name: str, a_key: str, b_key: str) -> None:
        if a_key not in ka.stats and b_key not in kb.stats:
            return
        va, vb = ka.mean(a_key), kb.mean(b_key)
        ok = (va != va and vb != vb) or math.isclose(va, vb, rel_tol=rel_tol, abs_tol=1e-9)
        rows.append({"kpi": name, "a": va, "b": vb, "ok": ok})
    for k in _GROUPS:
        add(k, k, k)
    for a_id, b_id in cmp.node_mapping.items():
        for k in _NODE_KPIS:
            add(f"node.{a_id}->{b_id}.{k}", f"node.{a_id}.{k}", f"node.{b_id}.{k}")
    for a_id, b_id in cmp.resource_mapping.items():
        for k in _RES_KPIS:
            add(f"resource.{a_id}->{b_id}.{k}", f"resource.{a_id}.{k}", f"resource.{b_id}.{k}")
    return ResultComparison(all(r["ok"] for r in rows), rows, rel_tol)
