"""Generate the SYNTHETIC TEST DATA files used by tests, docs and the end-to-end example.

    python examples/data/make_synthetic_data.py

Every file is generated from a known distribution with a fixed seed. They are NOT plant measurements and must never be
presented as such: file names start with SYNTHETIC_ (SimForge then always flags the dataset as synthetic) and the
end-to-end workbook carries a LEEME sheet saying so (and is imported with --synthetic).
"""

from __future__ import annotations

import csv
import datetime as dt
from pathlib import Path

import numpy as np

OUT = Path(__file__).parent / "synthetic"
LABEL = "SYNTHETIC TEST DATA - generated by examples/data/make_synthetic_data.py - NOT plant measurements"


def _csv(name: str, header: list[str], rows: list[list], delimiter: str = ",") -> None:
    with (OUT / name).open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, delimiter=delimiter)
        w.writerow(header)
        w.writerows(rows)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(20261001)
    # A. approximately constant times: N(120, 0.8) s, comma-separated, decimal point
    a = rng.normal(120, 0.8, 40)
    _csv("SYNTHETIC_A_constant.csv", ["ciclo", "tiempo_s"], [[i + 1, f"{v:.2f}"] for i, v in enumerate(a)])
    # B. positively skewed times: lognormal mean 45 s, sd 15 s (150 obs), semicolon, decimal point
    s2 = np.log(1 + (15 / 45) ** 2)
    b = rng.lognormal(np.log(45) - s2 / 2, np.sqrt(s2), 150)
    _csv("SYNTHETIC_B_skewed.csv", ["id", "tiempo (s)"], [[i + 1, f"{v:.2f}"] for i, v in enumerate(b)], delimiter=";")
    # C. exponential inter-arrival times, mean 90 s, with arrival timestamps (200 obs)
    c = rng.exponential(90, 200)
    t0 = dt.datetime(2026, 9, 1, 6, 0, 0)
    ts = t0 + np.cumsum(c) * dt.timedelta(seconds=1)
    _csv("SYNTHETIC_C_arrivals.csv", ["llegada", "intervalo_s"],
         [[t.strftime("%Y-%m-%d %H:%M:%S"), f"{v:.1f}"] for t, v in zip(ts, c)])
    # D. gamma times (k=9, theta=5 -> mean 45 s) with missing / non-numeric / negative / zero entries
    d = [f"{v:.1f}" for v in rng.gamma(9, 5, 60)]
    for i, bad in {3: "", 11: "n/a", 17: "-", 25: "-12.0", 33: "0", 41: "  ", 52: "?"}.items():
        d[i] = bad
    _csv("SYNTHETIC_D_missing.csv", ["muestra", "tiempo_s"], [[i + 1, v] for i, v in enumerate(d)])
    # E. N(60, 5) s with three gross values (a jam of 240 s, 300 s, and a 5 s mis-registration)
    e = list(np.round(rng.normal(60, 5, 80), 1))
    e[10], e[40], e[70] = 240.0, 300.0, 5.0
    _csv("SYNTHETIC_E_outliers.csv", ["n", "tiempo_s"], [[i + 1, v] for i, v in enumerate(e)])
    # F. European CSV: ';' separator, decimal comma, minutes (gamma k=16, theta=0.1 -> mean 1.6 min)
    f = rng.gamma(16, 0.1, 50)
    _csv("SYNTHETIC_F_decimal_comma.csv", ["pieza", "tiempo_min"], [[i + 1, f"{v:.2f}".replace(".", ",")] for i, v in enumerate(f)],
         delimiter=";")
    # H. by operator and product: operator B ~30 % slower, product Y ~ +20 s
    rows = []
    for i in range(160):
        op, prod = ("A", "B")[i % 2], ("X", "Y")[(i // 2) % 2]
        base = rng.gamma(25, 2.0)  # mean 50 s
        v = base * (1.3 if op == "B" else 1.0) + (20 if prod == "Y" else 0)
        rows.append([i + 1, f"{v:.1f}", op, prod, ("mañana", "tarde")[(i // 40) % 2]])
    _csv("SYNTHETIC_H_operator_product.csv", ["n", "tiempo_s", "operario", "producto", "turno"], rows)
    _xlsx_multisheet(rng)
    _xlsx_e2e(rng)
    (OUT / "README.md").write_text(
        "# SYNTHETIC TEST DATA\n\nTodos los archivos de esta carpeta son **datos sintéticos** generados por "
        "`examples/data/make_synthetic_data.py` a partir de distribuciones conocidas y semillas fijas.\n"
        "**No son medidas de planta** y no deben presentarse como tales.\n\n"
        "| Archivo | Caso | Generado con |\n|---|---|---|\n"
        "| SYNTHETIC_A_constant.csv | A. tiempos aproximadamente constantes | N(120, 0.8) s, n=40 |\n"
        "| SYNTHETIC_B_skewed.csv | B. tiempos sesgados positivos (separador ;) | lognormal media 45 s, sd 15 s, n=150 |\n"
        "| SYNTHETIC_C_arrivals.csv | C. llegadas exponenciales con marca de tiempo | Exp(media 90 s), n=200 |\n"
        "| SYNTHETIC_D_missing.csv | D. vacíos, 'n/a', '-', negativo, cero | Gamma(k=9, θ=5) s, n=60 |\n"
        "| SYNTHETIC_E_outliers.csv | E. outliers (240, 300, 5 s) | N(60, 5) s, n=80 |\n"
        "| SYNTHETIC_F_decimal_comma.csv | F. CSV europeo: ';' y coma decimal, minutos | Gamma(k=16, θ=0.1) min, n=50 |\n"
        "| SYNTHETIC_G_multisheet.xlsx | G. XLSX con varias hojas, fórmula, unidades por fila | ver hojas |\n"
        "| SYNTHETIC_H_operator_product.csv | H. por operario/producto/turno | Gamma(25, 2) s, B ×1.3, Y +20 s |\n"
        "| tiempos_montaje.xlsx | ejemplo end-to-end (hoja LEEME lo indica) | Gamma(k=16, θ=1.875) s/circuito, n=87 + incidencias |\n",
        encoding="utf-8")


def _save_reproducible(wb, path: Path) -> None:
    """openpyxl stamps the current time in docProps and in the zip entries: fix both so the bytes (and the dataset
    hash) are identical on every generation."""
    import io
    import zipfile
    fixed = dt.datetime(2026, 10, 1, 0, 0, 0)
    wb.properties.created = wb.properties.modified = fixed
    buf = io.BytesIO()
    wb.save(buf)
    src = zipfile.ZipFile(io.BytesIO(buf.getvalue()))
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as out:
        for info in src.infolist():
            data = src.read(info.filename)
            if info.filename == "docProps/core.xml":
                import re
                data = re.sub(rb"(<dcterms:modified[^>]*>)[^<]*", rb"\g<1>2026-10-01T00:00:00Z", data)
            zi = zipfile.ZipInfo(info.filename, date_time=(2026, 10, 1, 0, 0, 0))
            zi.compress_type = zipfile.ZIP_DEFLATED
            out.writestr(zi, data)


def _xlsx_multisheet(rng) -> None:
    from openpyxl import Workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "Info"
    ws["A1"] = LABEL
    m = wb.create_sheet("Montaje")
    m.append(["tiempo (s)", "operario", "media"])
    vals = rng.gamma(9, 5, 30)
    for i, v in enumerate(vals):
        m.append([round(float(v), 1), "A" if i % 2 else "B", None])
    m["C2"] = "=AVERAGE(A2:A31)"  # a formula: SimForge never evaluates it
    s = wb.create_sheet("Soldadura")
    s.append(["tiempo", "unidad"])
    for i, v in enumerate(rng.normal(200, 4, 24)):
        s.append([round(float(v) / 60, 3), "min"] if i % 3 == 0 else [round(float(v), 1), "s"])
    _save_reproducible(wb, OUT / "SYNTHETIC_G_multisheet.xlsx")


def _xlsx_e2e(rng) -> None:
    """tiempos_montaje.xlsx: manual assembly time PER CIRCUIT (4 circuits per rack in the e2e model)."""
    from openpyxl import Workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "LEEME"
    ws["A1"] = LABEL
    ws["A2"] = "Hoja1: tiempo de montaje manual por circuito, en segundos. Ejemplo end-to-end de docs/data_import.md."
    h = wb.create_sheet("Hoja1")
    h.append(["Fecha", "Operario", "Tiempo"])
    t = dt.datetime(2026, 9, 14, 7, 0, 0)
    vals = list(np.round(rng.gamma(16, 1.875, 87), 1))  # mean 30 s / circuit
    vals[20] = 95.0  # long cycle (screw dropped) - a real event or not? the engineer decides
    vals[61] = 88.5
    for i, v in enumerate(vals):
        t += dt.timedelta(seconds=float(v) * 4 + 15)
        h.append([t, ("Ana", "Luis")[i % 2], None if i == 44 else float(v)])  # row with a missing time
    _save_reproducible(wb, OUT / "tiempos_montaje.xlsx")


if __name__ == "__main__":
    main()
